### ISSUE TITLE
tf_static not synchronized

### ISSUE THREAD

**Issue by jdcast** [TommyChangUMD/ros-humble-ros1-bridge-builder#19]
Hi @TommyChangUMD do you expect /tf_static to be synchronized across the bridge?
Behavior that I'm seeing when using the parameter bridge is that the ros2 side sees all frames and in their proper transforms, whereas the ros1 side is missing many of the static frames altogether.

My parameter bridge yaml file (loaded on ros1 side) contains the following:
```
- topic: '/tf'
    type: 'tf2_msgs/msg/TFMessage'
- topic: '/tf_static'
  type: 'tf2_msgs/msg/TFMessage'
  queue_size: 1
  qos:
    history: 'keep_all'
    durability: 'transient_local'  
```
My work around so far has been to do simply add static_transform_publishers and/or urdf links/transforms for the missing frames on the ros1 side.
