### ISSUE TITLE
Time delay in ros2 topic

### ISSUE THREAD

**Issue by ZhongmouLi** [TommyChangUMD/ros-humble-ros1-bridge-builder#28]
Hi Tommy,

First of all, I must say thanks for your package as it is very helpful for me.

I have two questions about it. I found there is a huge time delay when I echo topics in ros2 which are published in ros1, as you can see here

![Image](https://github.com/user-attachments/assets/19120067-2d68-415e-ad15-acd01392c94b)

Then, I would like to ask how can I obtain ros1 topics that are related to octomap? Because I checked ```--print-pairs: Print a list of the supported ROS 2 <=> ROS 1 conversion pairs.``` and it seems octomap topics are not supported yet.

Thanks for your time.

**Comment by TommyChangUMD** [comment]
Hmm... Could you share the steps to reproduce this large time delay? Is ROS1 publishing at a constant rate, or in bursts?

About octomap, I have updated the Dockerfile and README.md.  It is an option now.  To enable it, do:
`docker build . --build-arg ADD_octomap_msgs=1 -t ros-humble-ros1-bridge-builder`

**Comment by TommyChangUMD** [comment]
OK.  Let me test it and get back to you.  By the way, how did you start the ROS2 Humble Docker container?  Did you mount the /dev/shm volume ?

**Comment by ZhongmouLi** [comment]
Hi @TommyChangUMD ,

Sorry to reply so late. I did not mount /dev/shm. 

Here is how I launch your pkg and my ros2 humble in Docker containers.

```yaml
ros2_humble_bridge_container:
    image: ros2_humble_bridge
    container_name: ros2_humble_bridge_container
    entrypoint: ""
    command: bash -c "exec bash"
    tty: true                                  # keep service on
    environment:
      - ROS_MASTER_URI=http://192.168.100.101:11311
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=132
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ROS_Briduge/humbel_host/ros_bridge_shared:/bridge
      # - /etc/localtime:/etc/localtime:ro
    # networks:
    #   macvlan_net:
    #     ipv4_address: 192.168.1.111
    network_mode: host
    ipc: host

  ros2_humble_rviz:
    image: ros2_humble_rviz
    container_name: ros2_humble_rviz
    entrypoint: ""
    command: bash -c "exec bash"
    tty: true                                  # keep service on
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=132
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ROS_Briduge/humbel_host/ros_bridge_shared:/bridge
    network_mode: host
    ipc: host

```
